from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel

from pymongo import MongoClient
from bson import ObjectId

import jwt
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from pwdlib import PasswordHash

from datetime import datetime, timedelta, timezone

# APP

app = FastAPI(
    title="E-commerce Customer Support System"
)

# DATABASE CONFIGURATION

URL = "mongodb://127.0.0.1:27017/"

client = MongoClient(URL)        #connects to MongoDB server

db = client["ecommerce_support_db"]   #selects the db

#creating collections
user_collection = db["users"]
ticket_collection = db["tickets"]
order_collection = db["orders"]
comment_collection = db["comments"]
category_collection = db["categories"]

# SECURITY CONFIGURATION


password_hash = PasswordHash.recommended()

SECRET_KEY = "EcommerceSupportSecurityKey-ChangeThis"

ALGORITHM = "HS256"

TOKEN_EXPIRE_MINS = 30

oauth2_scheme = OAuth2PasswordBearer(
    tokenUrl="/login"
)

# ROLE VALUES

CUSTOMER = 1
SUPPORT_AGENT = 2
TEAM_LEAD = 3
ADMIN = 4

# PYDANTIC SCHEMAS
# ---------------- USER ----------------(basically signup)

class UserCreate(BaseModel):
    username: str
    password: str
    role: int


class UserResponse(BaseModel):
    id: str
    username: str
    role: int


# ---------------- LOGIN ----------------
#its a format of response
class TokenResponse(BaseModel):
    access_token: str #actual token generated by backend(used by backend)
    token_type: str   #bearer, who has the token ie logged in person


# ---------------- TICKET ----------------

class TicketCreate(BaseModel):
    order_id: str
    title: str
    description: str
    category: str


class TicketStatusUpdate(BaseModel): #done by support agent
    status: str


class TicketAssign(BaseModel):   #done by team lead
    agent_id: str


# ---------------- COMMENT ----------------

class CommentCreate(BaseModel):   #done by support agent, he gives an overview of the ticket like can it be resolved or not
    message: str


# ---------------- CATEGORY ----------------

class CategoryCreate(BaseModel):   #it is a list of tickets/problems from which customers can choose
    name: str


# HELPER FUNCTIONS

def user_helper(user): #it will remove unneccessary stuffs from the collection ie "users"

    return {
        "id": str(user["_id"]),
        "username": user["username"],
        "role": user["role"]
    }


def ticket_helper(ticket):#it will remove unneccessary stuffs from the collection ie "tickets"

    return {
        "id": str(ticket["_id"]),
        "customer_id": ticket["customer_id"],
        "order_id": ticket["order_id"],
        "title": ticket["title"],
        "description": ticket["description"],
        "category": ticket["category"],
        "status": ticket["status"],
        "agent_id": ticket.get("agent_id")
    }


def comment_helper(comment): #it will remove unneccessary stuffs from the collection ie "commets"

    return {
        "id": str(comment["_id"]),
        "ticket_id": comment["ticket_id"],
        "user_id": comment["user_id"],
        "message": comment["message"]
    }

#category and order dont need helper function bz thy dont contain unneccessary stuffs
# CREATE JWT TOKEN

def create_token(username: str, role: int): 
#expire tells you the duration for open window of an website(ex moodle)
    expire = datetime.now(timezone.utc) + timedelta(
        minutes=TOKEN_EXPIRE_MINS
    )

#payload gives some info to the token generated 
    payload = {
        "sub": username,
        "role": role,
        "exp": expire
    }

#here jwt creates the actual tocken using secret key
#.encode is a fn of jwt lib, it takes info and creates jwt token by itself
    token = jwt.encode(
        payload,
        SECRET_KEY,
        algorithm=ALGORITHM
    )

    return token

# GET CURRENT USER

def get_current_user(
    token: str = Depends(oauth2_scheme)
):

    try:
        #.decode reads info in side token and verify it
        payload = jwt.decode(
            token,
            SECRET_KEY,
            algorithms=[ALGORITHM]
        )

        username = payload.get("sub")
        role = payload.get("role")

        if username is None or role is None:

            raise HTTPException(
                status_code=401,
                detail="Invalid token"
            )

    except jwt.ExpiredSignatureError:

        raise HTTPException(
            status_code=401,
            detail="Token has expired"
        )

    except jwt.InvalidTokenError:

        raise HTTPException(
            status_code=401,
            detail="Invalid token"
        )

    user = user_collection.find_one(
        {"username": username}
    )

    if user is None:

        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    return user


# ROLE CHECK

def require_role(*allowed_roles):

    def check_role(
        current_user=Depends(get_current_user)
    ):

        if current_user["role"] not in allowed_roles:

            raise HTTPException(
                status_code=403,
                detail="Permission denied"
            )

        return current_user

    return check_role


# 1. USER REGISTRATION


@app.post(
    "/users",
    status_code=201
)
def create_user(user: UserCreate):

    # Check valid role

    if user.role not in [
        CUSTOMER,
        SUPPORT_AGENT,
        TEAM_LEAD,
        ADMIN
    ]:

        raise HTTPException(
            status_code=400,
            detail="Invalid role"
        )

    existing_user = user_collection.find_one(
        {"username": user.username}
    )

    if existing_user:

        raise HTTPException(
            status_code=409,
            detail="Username already exists"
        )

    hashed_password = password_hash.hash(
        user.password
    )

    user_data = {

        "username": user.username,

        "password": hashed_password,

        "role": user.role
    }

    result = user_collection.insert_one(
        user_data
    )

    new_user = user_collection.find_one(
        {"_id": result.inserted_id}
    )

    return user_helper(new_user)


# 2. LOGIN


@app.post(
    "/login",
    response_model=TokenResponse
)
def login(
    form_data: OAuth2PasswordRequestForm = Depends()
):

    user = user_collection.find_one(
        {"username": form_data.username}
    )

    if user is None:

        raise HTTPException(
            status_code=401,
            detail="Invalid username or password"
        )

    if not password_hash.verify(
        form_data.password,
        user["password"]
    ):

        raise HTTPException(
            status_code=401,
            detail="Invalid username or password"
        )

    token = create_token(
        user["username"],
        user["role"]
    )

    return {
        "access_token": token,
        "token_type": "bearer"
    }


# ============================================================
# CUSTOMER APIs
# ============================================================


# ------------------------------------------------------------
# CUSTOMER - CREATE TICKET
# ------------------------------------------------------------

@app.post(
    "/customer/tickets",
    status_code=201
)
def customer_create_ticket(
    payload: TicketCreate,
    current_user=Depends(
        require_role(CUSTOMER)
    )
):

    # Check order ID

    if not ObjectId.is_valid(payload.order_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid order ID"
        )

    order = order_collection.find_one({
        "_id": ObjectId(payload.order_id)
    })

    if order is None:

        raise HTTPException(
            status_code=404,
            detail="Order not found"
        )

    # Check order belongs to customer

    if order["customer_id"] != str(
        current_user["_id"]
    ):

        raise HTTPException(
            status_code=403,
            detail="This order does not belong to you"
        )

    ticket_data = {

        "customer_id": str(
            current_user["_id"]
        ),

        "order_id": payload.order_id,

        "title": payload.title,

        "description": payload.description,

        "category": payload.category,

        "status": "NEW",

        "agent_id": None
    }

    result = ticket_collection.insert_one(
        ticket_data
    )

    return {
        "message": "Support ticket created successfully",
        "ticket_id": str(result.inserted_id)
    }


# ------------------------------------------------------------
# CUSTOMER - VIEW OWN TICKETS
# ------------------------------------------------------------

@app.get("/customer/tickets")
def customer_get_tickets(
    current_user=Depends(
        require_role(CUSTOMER)
    )
):

    tickets = ticket_collection.find({

        "customer_id": str(
            current_user["_id"]
        )

    })

    return [
        ticket_helper(ticket)
        for ticket in tickets
    ]


# ------------------------------------------------------------
# CUSTOMER - VIEW ONE TICKET
# ------------------------------------------------------------

@app.get("/customer/tickets/{ticket_id}")
def customer_get_ticket(
    ticket_id: str,
    current_user=Depends(
        require_role(CUSTOMER)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    if ticket["customer_id"] != str(
        current_user["_id"]
    ):

        raise HTTPException(
            status_code=403,
            detail="You cannot view this ticket"
        )

    return ticket_helper(ticket)


# ------------------------------------------------------------
# CUSTOMER - ADD COMMENT
# ------------------------------------------------------------

@app.post(
    "/customer/tickets/{ticket_id}/comments"
)
def customer_add_comment(
    ticket_id: str,
    payload: CommentCreate,
    current_user=Depends(
        require_role(CUSTOMER)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    if ticket["customer_id"] != str(
        current_user["_id"]
    ):

        raise HTTPException(
            status_code=403,
            detail="Permission denied"
        )

    comment_data = {

        "ticket_id": ticket_id,

        "user_id": str(
            current_user["_id"]
        ),

        "message": payload.message
    }

    result = comment_collection.insert_one(
        comment_data
    )

    return {
        "message": "Comment added successfully",
        "comment_id": str(result.inserted_id)
    }


# ------------------------------------------------------------
# CUSTOMER - CLOSE TICKET
# ------------------------------------------------------------

@app.put(
    "/customer/tickets/{ticket_id}/close"
)
def customer_close_ticket(
    ticket_id: str,
    current_user=Depends(
        require_role(CUSTOMER)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    if ticket["customer_id"] != str(
        current_user["_id"]
    ):

        raise HTTPException(
            status_code=403,
            detail="Permission denied"
        )

    if ticket["status"] != "RESOLVED":

        raise HTTPException(
            status_code=400,
            detail="Ticket must be resolved first"
        )

    ticket_collection.update_one(

        {"_id": ObjectId(ticket_id)},

        {
            "$set": {
                "status": "CLOSED"
            }
        }
    )

    return {
        "message": "Ticket closed successfully"
    }


# ============================================================
# SUPPORT AGENT APIs
# ============================================================


# ------------------------------------------------------------
# AGENT - VIEW ALL TICKETS
# ------------------------------------------------------------

@app.get("/agent/tickets")
def agent_get_all_tickets(
    current_user=Depends(
        require_role(SUPPORT_AGENT)
    )
):

    tickets = ticket_collection.find()

    return [
        ticket_helper(ticket)
        for ticket in tickets
    ]


# ------------------------------------------------------------
# AGENT - VIEW NEW TICKETS
# ------------------------------------------------------------

@app.get("/agent/tickets/new")
def agent_get_new_tickets(
    current_user=Depends(
        require_role(SUPPORT_AGENT)
    )
):

    tickets = ticket_collection.find({
        "status": "NEW"
    })

    return [
        ticket_helper(ticket)
        for ticket in tickets
    ]


# ------------------------------------------------------------
# AGENT - ASSIGN TICKET TO SELF
# ------------------------------------------------------------

@app.put(
    "/agent/tickets/{ticket_id}/assign"
)
def agent_assign_ticket(
    ticket_id: str,
    current_user=Depends(
        require_role(SUPPORT_AGENT)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    if ticket["status"] != "NEW":

        raise HTTPException(
            status_code=400,
            detail="Ticket is already assigned"
        )

    ticket_collection.update_one(

        {"_id": ObjectId(ticket_id)},

        {
            "$set": {

                "agent_id": str(
                    current_user["_id"]
                ),

                "status": "ASSIGNED"
            }
        }
    )

    return {
        "message": "Ticket assigned successfully"
    }


# ------------------------------------------------------------
# AGENT - VIEW MY TICKETS
# ------------------------------------------------------------

@app.get("/agent/my-tickets")
def agent_my_tickets(
    current_user=Depends(
        require_role(SUPPORT_AGENT)
    )
):

    tickets = ticket_collection.find({

        "agent_id": str(
            current_user["_id"]
        )

    })

    return [
        ticket_helper(ticket)
        for ticket in tickets
    ]


# ------------------------------------------------------------
# AGENT - UPDATE STATUS
# ------------------------------------------------------------

@app.put(
    "/agent/tickets/{ticket_id}/status"
)
def agent_update_status(
    ticket_id: str,
    payload: TicketStatusUpdate,
    current_user=Depends(
        require_role(SUPPORT_AGENT)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    if ticket.get("agent_id") != str(
        current_user["_id"]
    ):

        raise HTTPException(
            status_code=403,
            detail="Ticket is not assigned to you"
        )

    allowed_statuses = [
        "ASSIGNED",
        "IN_PROGRESS",
        "ON_HOLD",
        "RESOLVED"
    ]

    if payload.status not in allowed_statuses:

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket status"
        )

    ticket_collection.update_one(

        {"_id": ObjectId(ticket_id)},

        {
            "$set": {
                "status": payload.status
            }
        }
    )

    return {
        "message": "Ticket status updated successfully"
    }


# ------------------------------------------------------------
# AGENT - ADD COMMENT
# ------------------------------------------------------------

@app.post(
    "/agent/tickets/{ticket_id}/comments"
)
def agent_add_comment(
    ticket_id: str,
    payload: CommentCreate,
    current_user=Depends(
        require_role(SUPPORT_AGENT)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    if ticket.get("agent_id") != str(
        current_user["_id"]
    ):

        raise HTTPException(
            status_code=403,
            detail="Ticket is not assigned to you"
        )

    comment_data = {

        "ticket_id": ticket_id,

        "user_id": str(
            current_user["_id"]
        ),

        "message": payload.message
    }

    result = comment_collection.insert_one(
        comment_data
    )

    return {
        "message": "Comment added successfully",
        "comment_id": str(result.inserted_id)
    }


# ============================================================
# SUPPORT TEAM LEAD APIs
# ============================================================


# ------------------------------------------------------------
# TEAM LEAD - VIEW ALL TICKETS
# ------------------------------------------------------------

@app.get("/team-lead/tickets")
def team_lead_get_tickets(
    current_user=Depends(
        require_role(TEAM_LEAD)
    )
):

    tickets = ticket_collection.find()

    return [
        ticket_helper(ticket)
        for ticket in tickets
    ]


# ------------------------------------------------------------
# TEAM LEAD - ASSIGN / REASSIGN TICKET
# ------------------------------------------------------------

@app.put(
    "/team-lead/tickets/{ticket_id}/assign"
)
def team_lead_assign_ticket(
    ticket_id: str,
    payload: TicketAssign,
    current_user=Depends(
        require_role(TEAM_LEAD)
    )
):

    if not ObjectId.is_valid(ticket_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid ticket ID"
        )

    if not ObjectId.is_valid(payload.agent_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid agent ID"
        )

    agent = user_collection.find_one({
        "_id": ObjectId(payload.agent_id)
    })

    if agent is None:

        raise HTTPException(
            status_code=404,
            detail="Support Agent not found"
        )

    if agent["role"] != SUPPORT_AGENT:

        raise HTTPException(
            status_code=400,
            detail="Selected user is not a Support Agent"
        )

    ticket = ticket_collection.find_one({
        "_id": ObjectId(ticket_id)
    })

    if ticket is None:

        raise HTTPException(
            status_code=404,
            detail="Ticket not found"
        )

    ticket_collection.update_one(

        {"_id": ObjectId(ticket_id)},

        {
            "$set": {

                "agent_id": payload.agent_id,

                "status": "ASSIGNED"
            }
        }
    )

    return {
        "message": "Ticket assigned/reassigned successfully"
    }


# ------------------------------------------------------------
# TEAM LEAD - VIEW SUPPORT AGENTS
# ------------------------------------------------------------

@app.get("/team-lead/agents")
def team_lead_get_agents(
    current_user=Depends(
        require_role(TEAM_LEAD)
    )
):

    agents = user_collection.find({
        "role": SUPPORT_AGENT
    })

    return [
        user_helper(agent)
        for agent in agents
    ]


# ------------------------------------------------------------
# TEAM LEAD - MONITOR TICKETS
# ------------------------------------------------------------

@app.get("/team-lead/dashboard")
def team_lead_dashboard(
    current_user=Depends(
        require_role(TEAM_LEAD)
    )
):

    total = ticket_collection.count_documents({})

    new = ticket_collection.count_documents({
        "status": "NEW"
    })

    assigned = ticket_collection.count_documents({
        "status": "ASSIGNED"
    })

    in_progress = ticket_collection.count_documents({
        "status": "IN_PROGRESS"
    })

    on_hold = ticket_collection.count_documents({
        "status": "ON_HOLD"
    })

    resolved = ticket_collection.count_documents({
        "status": "RESOLVED"
    })

    closed = ticket_collection.count_documents({
        "status": "CLOSED"
    })

    return {

        "total_tickets": total,

        "NEW": new,

        "ASSIGNED": assigned,

        "IN_PROGRESS": in_progress,

        "ON_HOLD": on_hold,

        "RESOLVED": resolved,

        "CLOSED": closed
    }


# ============================================================
# ADMIN APIs
# ============================================================


# ------------------------------------------------------------
# ADMIN - VIEW ALL USERS
# ------------------------------------------------------------

@app.get("/admin/users")
def admin_get_users(
    current_user=Depends(
        require_role(ADMIN)
    )
):

    users = user_collection.find()

    return [
        user_helper(user)
        for user in users
    ]


# ------------------------------------------------------------
# ADMIN - DELETE USER
# ------------------------------------------------------------

@app.delete("/admin/users/{user_id}")
def admin_delete_user(
    user_id: str,
    current_user=Depends(
        require_role(ADMIN)
    )
):

    if not ObjectId.is_valid(user_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid user ID"
        )

    result = user_collection.delete_one({
        "_id": ObjectId(user_id)
    })

    if result.deleted_count == 0:

        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    return {
        "message": "User deleted successfully"
    }


# ------------------------------------------------------------
# ADMIN - CREATE CATEGORY
# ------------------------------------------------------------

@app.post(
    "/admin/categories",
    status_code=201
)
def admin_create_category(
    category: CategoryCreate,
    current_user=Depends(
        require_role(ADMIN)
    )
):

    existing = category_collection.find_one({
        "name": category.name
    })

    if existing:

        raise HTTPException(
            status_code=409,
            detail="Category already exists"
        )

    result = category_collection.insert_one({
        "name": category.name
    })

    return {
        "message": "Category created successfully",
        "category_id": str(result.inserted_id)
    }


# ------------------------------------------------------------
# ADMIN - VIEW CATEGORIES
# ------------------------------------------------------------

@app.get("/admin/categories")
def admin_get_categories(
    current_user=Depends(
        require_role(ADMIN)
    )
):

    categories = category_collection.find()

    return [
        {
            "id": str(category["_id"]),
            "name": category["name"]
        }
        for category in categories
    ]


# ------------------------------------------------------------
# ADMIN - DELETE CATEGORY
# ------------------------------------------------------------

@app.delete(
    "/admin/categories/{category_id}"
)
def admin_delete_category(
    category_id: str,
    current_user=Depends(
        require_role(ADMIN)
    )
):

    if not ObjectId.is_valid(category_id):

        raise HTTPException(
            status_code=400,
            detail="Invalid category ID"
        )

    result = category_collection.delete_one({
        "_id": ObjectId(category_id)
    })

    if result.deleted_count == 0:

        raise HTTPException(
            status_code=404,
            detail="Category not found"
        )

    return {
        "message": "Category deleted successfully"
    }